### ISSUE TITLE
你好 mac下没有封面呀

### ISSUE THREAD

**Issue by Sev73n** [nondanee/ncmdump#10]

**Comment by Sev73n** [comment]
![image](https://user-images.githubusercontent.com/16495885/50903542-6dead300-1461-11e9-8216-a4c65efad9ff.png)
如图 下载的mp3在mac下是能显示封面的
ncm下载后无法显示封面 转换后的mp3也不行

**Comment by Sev73n** [comment]
希望能再加两行代码 自动删除已经转换了的ncm格式音乐

**Comment by nondanee** [comment]
自动删除 `python app.py -d`
是用 macOS 的客户端下载的吗？麻烦提供一下客户端版本，我测试一下

**Comment by Sev73n** [comment]
我使用的是10.14.2 Python3 gui用的是另一位朋友打包的 我自己改了一下他的包，调用的是你的dump

**Comment by nondanee** [comment]
哦哦好
我是想问 ncm 是通过 macOS 的网易云客户端下载的还是？版本号是多少？
在 dump 里面没有删除逻辑（默认不删除）
你也自己加一下 `os.remove(path)` 嘛

**Comment by Sev73n** [comment]
好的 十分感谢 ！我的网易云版本是1.5.10（636）

**Comment by nondanee** [comment]
👌 好的，我去试一下

**Comment by nondanee** [comment]
已修复
