### ISSUE TITLE
下载下来完全不会用啊要死了？电脑小白？？？？

### ISSUE THREAD

**Issue by fyqJennifer** [nondanee/ncmdump#12]

**Comment by nondanee** [comment]
会用命令行的话用这个 https://github.com/yoki123/ncmdump 的 release
想用 GUI 的话用这个 https://github.com/anonymous5l/ncmdump-gui 的 release
不想下载也不在意 ID3 tag 缺失的话用这个 https://github.com/magic-akari/ncmc-web 的在线 demo

使用这个 python 版本的话
1. 需要 python 环境，python 2 或 python 3 都行
2. `pip install pycryptodome mutagen`
3. `python app.py`
