### ISSUE TITLE
Bytes required not bytearray

### ISSUE THREAD

**Issue by pingrunhuang** [nondanee/ncmdump#13]
Traceback (most recent call last):
  File "app.py", line 106, in <module>
    save = ncmdump.dump(path, name_format, args.skip)
  File "/Users/frank/dev/ncmdump/ncmdump.py", line 91, in dump
    data = XOR(data, stream)
TypeError: argument 1 must be bytes, not bytearray

Would you like me to fix it?

**Comment by nondanee** [comment]
Well I check the pycryptodome API documentation
https://pycryptodome.readthedocs.io/en/stable/src/util/util.html#Crypto.Util.strxor.strxor
It should support xor two bytearray, you're recommended to update dependency version first.
```
pip install pycryptodome -U
```
Or if you want to work with compatibility for old version, just go ahead, PR is welcomed.

**Comment by nondanee** [comment]
Oh, I notice that turn binary data to bytearray is redundant
I will fix it
Thanks for feedback
