### ISSUE TITLE
新版网易云客户端（mac 2.0.0（700））下载的ncm格式，不包含meta_data造成转换失败

### ISSUE THREAD

**Issue by elevenkey** [nondanee/ncmdump#14]
看了一下54行：meta_length = f.read(4) 读取到的是b'\x00\x00\x00\x00'
另外同一歌曲，老版本下载的文件是5.4M，新版（2.0.0 700）文件大小为4.3M
基本确定不包含meta信息了

**Comment by nondanee** [comment]
我试了下用 2.0.0 (730) 下载的 ncm 文件都包含 meta 信息，所以没办法 debug
能不能提供一下你的 ncm 文件，用 firefox send 就行了

**Comment by nondanee** [comment]
我按最坏情况改了，主要问题是缺 format 值。
虽然可以通过解密后检查 magic number，但是因为有 “跳过已转换的文件” 和 “自动处理命名冲突” 的逻辑，我还是在解密前用文件大小来判断（可能不一定准），能不解密就不解密（虽然现在解密不慢），麻烦测试一下。

**Comment by gaoxiaosong1113** [comment]
@nondanee   我这边遇到这个问题了，您给我留个邮箱，我发你一份 
ps：我的  704041637@qq.com
![image](https://user-images.githubusercontent.com/16183057/59209009-ee625b00-8bdc-11e9-8ab1-231a4610a8c1.png)

**Comment by nondanee** [comment]
@gaoxiaosong1113 
抱歉你这个不是我的代码
是用的别人 fork 的版本吗？
(报错提示的是语法错误)
f-string 需要 python3.6 以上才行

我的邮箱在 github profile 里有
发 ncm 文件的话建议用 [firefox send](https://send.firefox.com/)
