### ISSUE TITLE
发现有首歌无法转换报错 HeaderNotFoundError

### ISSUE THREAD

**Issue by chouchoui** [nondanee/ncmdump#18]
[Vbnd - thoughts of you](https://music.163.com/song?id=482636134)
```
Traceback (most recent call last):
  File "app.py", line 106, in <module>
    save = ncmdump.dump(path, name_format, args.skip)
  File "[Private]/Applications/ncmdump-python/ncmdump.py", line 108, in dump
    audio = mp3.MP3(output_path)
  File "[Private]/Library/Python/2.7/lib/python/site-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "[Private]/Library/Python/2.7/lib/python/site-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "[Private]/Library/Python/2.7/lib/python/site-packages/mutagen/id3/_file.py", line 423, in load
    self.info = self._Info(fileobj, offset)
  File "[Private]/Library/Python/2.7/lib/python/site-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "[Private]/Library/Python/2.7/lib/python/site-packages/mutagen/mp3/__init__.py", line 403, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
```

**Comment by nondanee** [comment]
@chouchoui 请发一下 ncm 文件，可以用 firefox send

**Comment by chouchoui** [comment]
[https://send.firefox.com/download/ced837d3ba41cb4f/#UXJsnkpqDcx5ihThj8hhog](https://send.firefox.com/download/ced837d3ba41cb4f/#UXJsnkpqDcx5ihThj8hhog)

**Comment by nondanee** [comment]
因为转换后根本不是 mp3 格式所以用 mutagen 写入 tag 会报错

然后我试了下这些版本
https://github.com/anonymous5l/ncmdump-gui (原作者的仓库)
https://github.com/NoColor2/ncmdump
https://github.com/yoki123/ncmdump
转换后均不是正确的 mp3 文件，也都无法正常播放

但是
https://github.com/magic-akari/ncmc-web
可以播放

我看了下源码发现他用了一个 13 字节的 gap
> ```offset += dataview.getUint32(offset + 5, true) + 13;```
> https://github.com/magic-akari/ncmc-web/blob/master/worker.js#L141

为什么跳过我也不知道，为什么之前没跳过也可以解码我也不知道
总之就很神奇

所以这张图应该是错的
https://github.com/yoki123/ncmdump/blob/master/asserts/ncm.png
cover data 和 music data 之间还有一个 13 字节的 gap

**Comment by nondanee** [comment]
因为转换后根本不是 mp3 格式所以用 mutagen 写入 tag 会报错

然后我试了下这些版本
https://github.com/anonymous5l/ncmdump-gui (原作者的仓库)
https://github.com/NoColor2/ncmdump
https://github.com/yoki123/ncmdump
转换后均不是正确的 mp3 文件，也都无法正常播放

但是
https://github.com/magic-akari/ncmc-web
可以播放

我看了下源码发现他用了一个 13 字节的 gap
> ```offset += dataview.getUint32(offset + 5, true) + 13;```
> https://github.com/magic-akari/ncmc-web/blob/master/worker.js#L141

然后发现他用的 `dataview.getUint32(offset + 5, true)` 作为 image_size 来跳过
这个东西其实是之前的 crc32，我去验证了下这并不是图片的 crc32
13 字节 = 5 (gap) + 4(mp3数据的真实偏移) + 4(图片实际大小)

之前没发现是因为，两个 4 字节的数值相等
这首歌的封面图特别小，这两个数值不一样（可能有填充）导致偏移错了，解码失败
