### ISSUE TITLE
可以改成pycryptodome么，手机上termux不能安装pycrypto

### ISSUE THREAD

**Issue by herexf** [nondanee/ncmdump#2]
如题，怎么也安装不了，
查了网上，说建议用pycryptodome

我先自己试试看。谢谢

**Comment by herexf** [comment]
搞定了，用的pip install pycryptodomex

然后可以手机上转ncm，太感谢了。

**Comment by nondanee** [comment]
欸你装的上吗？我试了下在termux里dome和domex都装不上啊😂
如果用domex，13行要改成`from Cryptodome.Cipher import AES`吧
你也可以直接用[JamieDummy/NCM_dump](https://github.com/JamieDummy/NCM_dump)这个fork
如果是dome应该不用改代码

**Comment by herexf** [comment]
我两个dome和domex都装了，没改源码，也可以直接运行，没问题的。

谢谢


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by herexf** [comment]
[Image]


[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by herexf** [comment]
手机上只能用你的代码，
JamieDummy/NCM_dump的因为改成了GUI，手机上的termux不支持gui，没有Tkinter。

没办法，谢谢啦
