### ISSUE TITLE
pip报错

### ISSUE THREAD

**Issue by NineFox1988** [nondanee/ncmdump#23]
PS C:\Users\nfox> pip install git+https://github.com/nondanee/ncmdump.git
Looking in indexes: https://pypi.douban.com/simple
Collecting git+https://github.com/nondanee/ncmdump.git
  Cloning https://github.com/nondanee/ncmdump.git to c:\users\nfox\appdata\local\temp\pip-req-build-rbkon65z
  Running command git clone -q https://github.com/nondanee/ncmdump.git 'C:\Users\nfox\AppData\Local\Temp\pip-req-build-rbkon65z'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nfox\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nfox\\AppData\\Local\\Temp\\pip-req-build-rbkon65z\\setup.py'"'"'; __file__='"'"'C:\\Users\\nfox\\AppData\\Local\\Temp\\pip-req-build-rbkon65z\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\nfox\AppData\Local\Temp\pip-req-build-rbkon65z\pip-egg-info'
         cwd: C:\Users\nfox\AppData\Local\Temp\pip-req-build-rbkon65z\
    Complete output (12 lines):
    Traceback (most recent call last):
      File "C:\Users\nfox\AppData\Local\Temp\pip-req-build-rbkon65z\setup.py", line 7, in <module>
        from pip._internal.download import PipSession
    ModuleNotFoundError: No module named 'pip._internal.download'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\nfox\AppData\Local\Temp\pip-req-build-rbkon65z\setup.py", line 9, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nondanee** [comment]
你的 pip 版本是多少？

**Comment by NineFox1988** [comment]
pip 20.0.2 from c:\users\nfox\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

**Comment by nondanee** [comment]
查了下是这个问题 https://github.com/pypa/pip/issues/7645
