### ISSUE TITLE
使用时出错: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by clarifiism** [nondanee/ncmdump#25]
报错信息如下:

>Traceback (most recent call last):
>  File ".\app.py", line 116, in main
>    save = dump(path, name_format, not args.cover)
>  File "C:\Users\jion\Downloads\ncmdump-master (1)\ncmdump-master\ncmdump\core.py", line 65, in dump
>    meta_data = json.loads(meta_data[6:])
>  File "C:\Users\jion\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
>    return _default_decoder.decode(s)
>  File "C:\Users\jion\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
>    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>  File "C:\Users\jion\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
>    raise JSONDecodeError("Expecting value", s, err.value) from None
>json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nondanee** [comment]
麻烦提供一下 ncm 文件
