### ISSUE TITLE
macOS网易云音乐2.3.2(832)下载的小部分无法正确解密meta

### ISSUE THREAD

**Issue by ehznahz** [nondanee/ncmdump#26]
专辑封面无法显示，meta信息编码错误，但可以正常播放，如：
![rDhnn8](https://zhan-pics.oss-cn-beijing.aliyuncs.com/uPic/rDhnn8.png)
![8vVptS](https://zhan-pics.oss-cn-beijing.aliyuncs.com/uPic/8vVptS.jpg)

**Comment by nondanee** [comment]
应该是 ncm 里没有 meta 信息，这个是音频文件自带的 ID3tag
ncm 文件发一下 (可以用 firefox send)

**Comment by ehznahz** [comment]
> 应该是 ncm 里没有 meta 信息，这个是音频文件自带的 ID3tag
> ncm 文件发一下 (可以用 firefox send)

这是出现异常的文件之一：
https://send.firefox.com/download/a450d935be330ad8/#SCP_9flH2BkD_DCoizvH0Q

**Comment by nondanee** [comment]
@ehznahz 需要 ncm 源文件哦

**Comment by ehznahz** [comment]
Sorry,传错了。https://send.firefox.com/download/3878140291628dc4/#uFwDnmJcPfew5p9hqXAwRg

**Comment by nondanee** [comment]
看过了，这个 ncm 文件里确实没有 meta 信息 #14
当没有 meta 时 ncmdump 不会也无法写入 ID3tag
所以解密出来的就是网易云的源文件
md5: 386044c590c366962783169d8c985359
你看到的信息是源文件自带的

你可以手动修改
或者
使用 [163marker](https://github.com/nondanee/163marker) 写入网易云指定歌曲的信息
```sh
$ 163marker "西村由紀江 - 手纸.mp3" "https://music.163.com/#/song?id=669238"
```
