### ISSUE TITLE
一个错误

### ISSUE THREAD

**Issue by Lyon1994** [nondanee/ncmdump#5]
首先，给你赞一个，这工具很好用，
然后这里有个bug，app.py文件第85行你这边写错了
![image](https://user-images.githubusercontent.com/8456652/47264505-09e3fd00-d54b-11e8-97fb-e6823368850b.png)

![image](https://user-images.githubusercontent.com/8456652/47264533-7e1ea080-d54b-11e8-91d3-91302ec22739.png)

**Comment by nondanee** [comment]
嘶~马上修！😂
