### ISSUE TITLE
我想发布一个termux已部署版本包含你的脚本于32位arm机型使用的环境

### ISSUE THREAD

**Issue by logic10492** [nondanee/ncmdump#8]
我将发布于酷安网上
包含一个已部署的termux
和您的源码
之前酷安上已经有人发布了适用于arm64的版本 但因为python平台不同 导致它不能运行于arm机型上
我现在已经在arm机型上完成部署
现征求您的同意

**Comment by Cyanogen-Mod** [comment]
是有一点慢, 但在手机上操作方便也无所谓啦 😂

**Comment by nondanee** [comment]
那随便咯 😂
