### ISSUE TITLE
tag中含有冒号的不能正常导出

### ISSUE THREAD

**Issue by Avalon** [nondanee/ncmdump#9]
比如歌名为`Aimer - Re:frain.ncm` 只会创立一个空的 `Aimer - Ref` 文件，但是还是要一段时间才能结束，我推测是写入的操作找不到要写入的对象（因为文件名创建的不对）

**Comment by nondanee** [comment]
你用了哪种啊？
`python ncmdump.py` 还是 `python app.py` ？

**Comment by nondanee** [comment]
在什么平台运行呢？win？mac？linux？

**Comment by Avalon** [comment]
没问题了 我还用的是之前的版本，新版本已经解决了 运行`ncmdump.py` 和用`app.py`调用都可以成功，而且速度也比之前的快很多啊
thanks! 👍
